### ISSUE TITLE
Restoring with --only-volumes still tries tp restore containers

### ISSUE THREAD

**Issue by inlightmedia** [tlaanemaa/backup-docker#19]
When trying to restore a back up that was run with
```sh
./node_modules/.bin/backup-docker backup postgres --only-volumes
```

I get the following error:

```sh
 ./node_modules/.bin/backup-docker restore postgres --only-volumes
== Restoring container: postgres ==
ENOENT: no such file or directory, open '/Users/home/Desktop/my-app/containers/postgres.json'
```

It seems like it is trying to restore the container despite the flag being present to only restore the volume.

Maybe you cannot backup with --only-volumes set?

**Comment by tlaanemaa** [comment]
Hey 👋 
Sorry for the late reply.

Yea this might be a bit misleading, it still relies on the container spec to restore the volumes.
The reason being that the container is the "entry" point for any operation, for example, see how you still need to provide container name when backing up or restoring just volumes. It uses the container's spec to know which volumes to backup or restore, by looking through which volumes are attached to the container.

Your assumption is correct, you shouldn't back up with `--only-volumes` set to avoid this kind of a situation.

The fact that you can backup with `--only-volumes` seems to be a mistake and should be fixed. I'll try to get to removing it at some point, meanwhile, PRs are most welcome if you're willing :D

Let me know if you need more help.
