### ISSUE TITLE
Exclude container

### ISSUE THREAD

**Issue by CarlosLopezES** [tlaanemaa/backup-docker#20]
Hi,

Is possible to exclude some containers from the backup command? We have an issue with celery workers on backup, and will be great to exclude it from backup to avoid this problem.

Thanks!

**Comment by tlaanemaa** [comment]
Hey

Hmm, I don't think you can.
What you can do however is to list the containers you do want to backup. So if you've got a static list of containers, you could list all of the containers you do want to backup instead.

```sh
backup-docker container1 container2 container3
```

**Comment by CarlosLopezES** [comment]
Good point! Thanks!
