### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by alexblueskypilot** [tlaanemaa/backup-docker#29]
Hi,

When trying to run the script I have this error:

`Unexpected token {`

How can I fix that?

Thanks,

Alex.

**Comment by tlaanemaa** [comment]
Hey

I assume you mean the scripted backup scripts from [here](https://github.com/tlaanemaa/backup-docker/issues/16)
Do you know where the error occurs? Does it give you a line number or something like that?
This seems very much like a syntax error but I checked the scripts and they seemed fine 🤔

**Comment by alexblueskypilot** [comment]
Hi!

No, I just run the command and the error appear then the script stops:

root@23-226-107-38:~# backup-docker backup
Unexpected token {

Is there a specific log file or something I can check? I tried in root and normal user with sudo, same issue.

Thanks,

Alex.

**Comment by alexblueskypilot** [comment]
I tried to reinstall it and got some errors as well:

loadDep:ssh2 → 304        ▐ ╢███████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
/usr/local/bin/backup-docker -> /usr/local/lib/node_modules/backup-docker/bin/run.js

> cpu-features@0.0.2 install /usr/local/lib/node_modules/backup-docker/node_modules/cpu-features
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/build'
  ACTION Configuring dependencies /usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build/Makefile
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for getauxval
-- Looking for getauxval - found
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build
  TOUCH Release/obj.target/config_deps.stamp
  ACTION Building dependencies /usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build/libcpu_features.a
make[1]: Entering directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
make[2]: Entering directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
make[3]: Entering directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
Scanning dependencies of target unix_based_hardware_detection
make[3]: Leaving directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
make[3]: Entering directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
[ 11%] Building C object CMakeFiles/unix_based_hardware_detection.dir/src/hwcaps.c.o
[ 22%] Building C object CMakeFiles/unix_based_hardware_detection.dir/src/unix_features_aggregator.c.o
make[3]: Leaving directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
[ 22%] Built target unix_based_hardware_detection
make[3]: Entering directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
Scanning dependencies of target utils
make[3]: Leaving directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
make[3]: Entering directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
[ 33%] Building C object CMakeFiles/utils.dir/src/filesystem.c.o
[ 44%] Building C object CMakeFiles/utils.dir/src/stack_line_reader.c.o
[ 55%] Building C object CMakeFiles/utils.dir/src/string_view.c.o
make[3]: Leaving directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
[ 55%] Built target utils
make[3]: Entering directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
Scanning dependencies of target cpu_features
make[3]: Leaving directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
make[3]: Entering directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
[ 66%] Building C object CMakeFiles/cpu_features.dir/src/cpuinfo_x86.c.o
[ 77%] Linking C static library libcpu_features.a
make[3]: Leaving directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
[ 77%] Built target cpu_features
make[3]: Entering directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
Scanning dependencies of target list_cpu_features
make[3]: Leaving directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
make[3]: Entering directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
[ 88%] Building C object CMakeFiles/list_cpu_features.dir/src/utils/list_cpu_features.c.o
[100%] Linking C executable list_cpu_features
make[3]: Leaving directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
[100%] Built target list_cpu_features
make[2]: Leaving directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
make[1]: Leaving directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/deps/cpu_features/build'
  TOUCH Release/obj.target/build_deps.stamp
  CXX(target) Release/obj.target/cpufeatures/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/cpufeatures.node
  COPY Release/cpufeatures.node
make: Leaving directory '/usr/local/lib/node_modules/backup-docker/node_modules/cpu-features/build'

> ssh2@1.5.0 install /usr/local/lib/node_modules/backup-docker/node_modules/ssh2
> node install.js

make: Entering directory '/usr/local/lib/node_modules/backup-docker/node_modules/ssh2/lib/protocol/crypto/build'
  CXX(target) Release/obj.target/sshcrypto/src/binding.o
../src/binding.cc: In member function ‘void ChaChaPolyCipher::clear()’:
../src/binding.cc:88:7: error: ‘EVP_MD_CTX_free’ was not declared in this scope
       EVP_MD_CTX_free(md_ctx_);
       ^~~~~~~~~~~~~~~
../src/binding.cc:88:7: note: suggested alternative: ‘EVP_MD_CTX_create’
       EVP_MD_CTX_free(md_ctx_);
       ^~~~~~~~~~~~~~~
       EVP_MD_CTX_create
../src/binding.cc: In member function ‘ErrorType ChaChaPolyCipher::init(unsigned char*, size_t)’:
../src/binding.cc:111:23: error: ‘EVP_MD_CTX_new’ was not declared in this scope
         || (md_ctx_ = EVP_MD_CTX_new()) == nullptr
                       ^~~~~~~~~~~~~~
../src/binding.cc:111:23: note: suggested alternative: ‘EVP_MD_CTX_init’
         || (md_ctx_ = EVP_MD_CTX_new()) == nullptr
                       ^~~~~~~~~~~~~~
                       EVP_MD_CTX_init
../src/binding.cc: In member function ‘ErrorType ChaChaPolyCipher::encrypt(unsigned char*, uint32_t, uint32_t)’:
../src/binding.cc:220:47: error: ‘EVP_PKEY_POLY1305’ was not declared in this scope
       polykey_ = EVP_PKEY_new_raw_private_key(EVP_PKEY_POLY1305,
                                               ^~~~~~~~~~~~~~~~~
../src/binding.cc:220:47: note: suggested alternative: ‘EVP_PKEY_get1_DH’
       polykey_ = EVP_PKEY_new_raw_private_key(EVP_PKEY_POLY1305,
                                               ^~~~~~~~~~~~~~~~~
                                               EVP_PKEY_get1_DH
../src/binding.cc:220:18: error: ‘EVP_PKEY_new_raw_private_key’ was not declared in this scope
       polykey_ = EVP_PKEY_new_raw_private_key(EVP_PKEY_POLY1305,
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:220:18: note: suggested alternative: ‘EVP_PKEY_new_mac_key’
       polykey_ = EVP_PKEY_new_raw_private_key(EVP_PKEY_POLY1305,
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  EVP_PKEY_new_mac_key
../src/binding.cc:240:9: error: ‘EVP_DigestSign’ was not declared in this scope
     if (EVP_DigestSign(md_ctx_,
         ^~~~~~~~~~~~~~
../src/binding.cc:240:9: note: suggested alternative: ‘EVP_DigestSignInit’
     if (EVP_DigestSign(md_ctx_,
         ^~~~~~~~~~~~~~
         EVP_DigestSignInit
../src/binding.cc: In member function ‘ErrorType AESGCMCipher::init(const char*, unsigned char*, size_t, unsigned char*, size_t)’:
../src/binding.cc:392:36: error: ‘EVP_CTRL_AEAD_SET_IVLEN’ was not declared in this scope
     if (!EVP_CIPHER_CTX_ctrl(ctx_, EVP_CTRL_AEAD_SET_IVLEN, iv_len, nullptr)) {
                                    ^~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:392:36: note: suggested alternative: ‘EVP_CTRL_GCM_SET_IVLEN’
     if (!EVP_CIPHER_CTX_ctrl(ctx_, EVP_CTRL_AEAD_SET_IVLEN, iv_len, nullptr)) {
                                    ^~~~~~~~~~~~~~~~~~~~~~~
                                    EVP_CTRL_GCM_SET_IVLEN
../src/binding.cc: In member function ‘ErrorType AESGCMCipher::encrypt(unsigned char*, uint32_t)’:
../src/binding.cc:474:29: error: ‘EVP_CTRL_AEAD_GET_TAG’ was not declared in this scope
                             EVP_CTRL_AEAD_GET_TAG,
                             ^~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:474:29: note: suggested alternative: ‘EVP_CTRL_CCM_GET_TAG’
                             EVP_CTRL_AEAD_GET_TAG,
                             ^~~~~~~~~~~~~~~~~~~~~
                             EVP_CTRL_CCM_GET_TAG
../src/binding.cc: In member function ‘void GenericCipher::clear()’:
../src/binding.cc:614:7: error: ‘HMAC_CTX_free’ was not declared in this scope
       HMAC_CTX_free(ctx_hmac_);
       ^~~~~~~~~~~~~
../src/binding.cc:614:7: note: suggested alternative: ‘HMAC_CTX_copy’
       HMAC_CTX_free(ctx_hmac_);
       ^~~~~~~~~~~~~
       HMAC_CTX_copy
../src/binding.cc: In member function ‘ErrorType GenericCipher::init(const char*, unsigned char*, size_t, unsigned char*, size_t, const char*, unsigned char*, size_t, int)’:
../src/binding.cc:694:22: error: ‘HMAC_CTX_new’ was not declared in this scope
     if ((ctx_hmac_ = HMAC_CTX_new()) == nullptr
                      ^~~~~~~~~~~~
../src/binding.cc:694:22: note: suggested alternative: ‘HMAC_CTX_init’
     if ((ctx_hmac_ = HMAC_CTX_new()) == nullptr
                      ^~~~~~~~~~~~
                      HMAC_CTX_init
../src/binding.cc: In member function ‘void ChaChaPolyDecipher::clear()’:
../src/binding.cc:956:7: error: ‘EVP_MD_CTX_free’ was not declared in this scope
       EVP_MD_CTX_free(md_ctx_);
       ^~~~~~~~~~~~~~~
../src/binding.cc:956:7: note: suggested alternative: ‘EVP_MD_CTX_create’
       EVP_MD_CTX_free(md_ctx_);
       ^~~~~~~~~~~~~~~
       EVP_MD_CTX_create
../src/binding.cc: In member function ‘ErrorType ChaChaPolyDecipher::init(unsigned char*, size_t)’:
../src/binding.cc:979:23: error: ‘EVP_MD_CTX_new’ was not declared in this scope
         || (md_ctx_ = EVP_MD_CTX_new()) == nullptr
                       ^~~~~~~~~~~~~~
../src/binding.cc:979:23: note: suggested alternative: ‘EVP_MD_CTX_init’
         || (md_ctx_ = EVP_MD_CTX_new()) == nullptr
                       ^~~~~~~~~~~~~~
                       EVP_MD_CTX_init
../src/binding.cc: In member function ‘ErrorType ChaChaPolyDecipher::decrypt(unsigned char*, uint32_t, unsigned char*, uint32_t)’:
../src/binding.cc:1097:47: error: ‘EVP_PKEY_POLY1305’ was not declared in this scope
       polykey_ = EVP_PKEY_new_raw_private_key(EVP_PKEY_POLY1305,
                                               ^~~~~~~~~~~~~~~~~
../src/binding.cc:1097:47: note: suggested alternative: ‘EVP_PKEY_get1_DH’
       polykey_ = EVP_PKEY_new_raw_private_key(EVP_PKEY_POLY1305,
                                               ^~~~~~~~~~~~~~~~~
                                               EVP_PKEY_get1_DH
../src/binding.cc:1097:18: error: ‘EVP_PKEY_new_raw_private_key’ was not declared in this scope
       polykey_ = EVP_PKEY_new_raw_private_key(EVP_PKEY_POLY1305,
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:1097:18: note: suggested alternative: ‘EVP_PKEY_new_mac_key’
       polykey_ = EVP_PKEY_new_raw_private_key(EVP_PKEY_POLY1305,
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  EVP_PKEY_new_mac_key
../src/binding.cc: In member function ‘ErrorType AESGCMDecipher::init(const char*, unsigned char*, size_t, unsigned char*, size_t)’:
../src/binding.cc:1353:36: error: ‘EVP_CTRL_AEAD_SET_IVLEN’ was not declared in this scope
     if (!EVP_CIPHER_CTX_ctrl(ctx_, EVP_CTRL_AEAD_SET_IVLEN, iv_len, nullptr)) {
                                    ^~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:1353:36: note: suggested alternative: ‘EVP_CTRL_GCM_SET_IVLEN’
     if (!EVP_CIPHER_CTX_ctrl(ctx_, EVP_CTRL_AEAD_SET_IVLEN, iv_len, nullptr)) {
                                    ^~~~~~~~~~~~~~~~~~~~~~~
                                    EVP_CTRL_GCM_SET_IVLEN
../src/binding.cc: In member function ‘ErrorType AESGCMDecipher::decrypt(unsigned char*, uint32_t, unsigned char*, unsigned char*)’:
../src/binding.cc:1426:35: error: ‘EVP_CTRL_AEAD_SET_TAG’ was not declared in this scope
     if (EVP_CIPHER_CTX_ctrl(ctx_, EVP_CTRL_AEAD_SET_TAG, 16, tag) != 1) {
                                   ^~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:1426:35: note: suggested alternative: ‘EVP_CTRL_GCM_SET_TAG’
     if (EVP_CIPHER_CTX_ctrl(ctx_, EVP_CTRL_AEAD_SET_TAG, 16, tag) != 1) {
                                   ^~~~~~~~~~~~~~~~~~~~~
                                   EVP_CTRL_GCM_SET_TAG
../src/binding.cc: In member function ‘void GenericDecipher::clear()’:
../src/binding.cc:1586:7: error: ‘HMAC_CTX_free’ was not declared in this scope
       HMAC_CTX_free(ctx_hmac_);
       ^~~~~~~~~~~~~
../src/binding.cc:1586:7: note: suggested alternative: ‘HMAC_CTX_copy’
       HMAC_CTX_free(ctx_hmac_);
       ^~~~~~~~~~~~~
       HMAC_CTX_copy
../src/binding.cc: In member function ‘ErrorType GenericDecipher::init(const char*, unsigned char*, size_t, unsigned char*, size_t, const char*, unsigned char*, size_t, int, size_t)’:
../src/binding.cc:1667:22: error: ‘HMAC_CTX_new’ was not declared in this scope
     if ((ctx_hmac_ = HMAC_CTX_new()) == nullptr
                      ^~~~~~~~~~~~
../src/binding.cc:1667:22: note: suggested alternative: ‘HMAC_CTX_init’
     if ((ctx_hmac_ = HMAC_CTX_new()) == nullptr
                      ^~~~~~~~~~~~
                      HMAC_CTX_init
sshcrypto.target.mk:97: recipe for target 'Release/obj.target/sshcrypto/src/binding.o' failed
make: *** [Release/obj.target/sshcrypto/src/binding.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/backup-docker/node_modules/ssh2/lib/protocol/crypto/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-161-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "--target=v8.10.0" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/backup-docker/node_modules/ssh2/lib/protocol/crypto
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Failed to build optional crypto binding
/usr/local/lib
└─┬ backup-docker@1.5.5 
  ├── commander@4.1.1 
  ├─┬ dockerode@3.3.1 
  │ ├─┬ docker-modem@3.0.3 
  │ │ ├─┬ debug@4.3.3 
  │ │ │ └── ms@2.1.2 
  │ │ ├─┬ readable-stream@3.6.0 
  │ │ │ ├── inherits@2.0.4 
  │ │ │ ├─┬ string_decoder@1.3.0 
  │ │ │ │ └── safe-buffer@5.2.1 
  │ │ │ └── util-deprecate@1.0.2 
  │ │ ├── split-ca@1.0.1 
  │ │ └─┬ ssh2@1.5.0 
  │ │   ├─┬ asn1@0.2.6 
  │ │   │ └── safer-buffer@2.1.2 
  │ │   ├─┬ bcrypt-pbkdf@1.0.2 
  │ │   │ └── tweetnacl@0.14.5 
  │ │   ├── cpu-features@0.0.2 
  │ │   └── nan@2.15.0 
  │ └─┬ tar-fs@2.0.1 
  │   ├── chownr@1.1.4 
  │   ├── mkdirp-classic@0.5.3 
  │   ├─┬ pump@3.0.0 
  │   │ ├── end-of-stream@1.4.4 
  │   │ └─┬ once@1.4.0 
  │   │   └── wrappy@1.0.2 
  │   └─┬ tar-stream@2.2.0 
  │     ├─┬ bl@4.1.0 
  │     │ └─┬ buffer@5.7.1 
  │     │   ├── base64-js@1.5.1 
  │     │   └── ieee754@1.2.1 
  │     └── fs-constants@1.0.0 
  └── limit-async@1.3.0

**Comment by alexblueskypilot** [comment]
Hi! Any idea on what I can try to fix that? Thanks!

**Comment by tlaanemaa** [comment]
Hey, sorry for the late reply.
Sorry, I don't have a lot of answers here, I haven't seen this before 🤔
It seems like you have an issue with `node-gyp` not being able to run `make`
> gyp ERR! stack Error: make failed with exit code: 2

What operating system are you on? I just tried on MacOS 12.1 and it installed and ran without a hitch 🤔
Also, are you on x86 or ARM? For example, if it's an M1 Mac then that might have an effect. I have tested and it worked on a Raspberry PI 4 but I don't have an M1 mac to test with sadly :/

See if you can figure out the `node-gyp` issue and if it works then :)
Let me know if you need more help!

**Comment by tlaanemaa** [comment]
Hey 👋
I hope you managed to get it working.
This seems inactive so I'll close it for now but please feel free to reopen if you still need help.
